# Generated by Django 5.0.1 on 2024-01-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
