# Generated by Django 5.0.1 on 2024-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
