# Generated by Django 5.0.1 on 2024-01-23 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_cloudinary_image_url_alter_post_profile'),
        ('profiles', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cloudinary_image_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='profiles.profile'),
        ),
    ]
