# Generated by Django 5.0.1 on 2024-01-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../7190932_ugiaz9.png', upload_to='images/'),
        ),
    ]
