# Generated by Django 5.0.1 on 2024-01-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
