# Generated by Django 5.0.1 on 2024-01-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_pfp_ivf3fa', upload_to='', verbose_name='image'),
        ),
    ]
