# Generated by Django 5.0.1 on 2024-01-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='7190932_ugiaz9.png'),
        ),
    ]
