# Generated by Django 5.0.1 on 2024-01-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='Default_pfp.svg_zssa2m.png'),
        ),
    ]
