# Generated by Django 5.0.1 on 2024-01-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='Default_pfp.svg_zssa2m.png', upload_to='profiles/'),
        ),
    ]
