# Generated by Django 5.0.1 on 2024-01-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0017_remove_post_user'),
        ('profiles', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profile', 'post')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
